Repository akademia-envelo-3/MELO-front, pull requests merged in 2023-01, with the labels that each got.

#26 Netlify deploy config
  netlify.toml
  package-lock.json
Labels: tech

#34 Fe 9 spinner dots
  src/app/core/theme.component.ts
  src/app/shared/index.ts
  src/app/shared/ui/spinner-dots.component.scss
  src/app/shared/ui/spinner-dots.component.ts
  src/styles.scss
Labels: cr-ok

#63 feat: add colors to design system in styles.scss
  src/styles.scss
Labels: cr/qa urgent lvl1

#43 Fe 4 add power icon
  src/app/core/theme.component.scss
  src/app/core/theme.component.ts
  src/app/shared/ui/index.ts
  src/app/shared/ui/power-icon/power-icon.component.ts
  src/app/shared/ui/power-icon/power-icon.html
  src/app/shared/ui/power-icon/power-icon.scss
Labels: cr-ok

#39 Fe 16 add form submit result view
  src/app/core/theme.component.ts
  src/app/shared/ui/form-result-view/form-result-view-component.scss
  src/app/shared/ui/form-result-view/form-result-view.component.ts
  src/app/shared/ui/index.ts
  src/app/shared/ui/spinner-dots/spinner-dots.component.scss
  src/app/shared/ui/spinner-dots/spinner-dots.component.ts
  src/assets/form-result-icons/confirm-icon.svg
  src/assets/form-result-icons/error-icon.svg
  src/styles.scss
Labels: cr-ok

#61 Fe 27 event service refactor
  src/app/features/event/event-api.service.ts
  src/app/features/event/event.state.service.ts
  src/app/features/event/index.ts
Labels: cr-ok
